default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages:
  - pre-commit
  - manual

repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.10
        args: ["--line-length=120"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        name: ruff-lint
        args:
          [
            "--select=E,F,W,I,UP,B,SIM,C4,S,NPY,PTH",
            "--line-length=120",
            "--ignore=S101,S311,S603,S607,S602,S104,S310",
          ]
        language_version: python3.10

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: pydoclint
        name: pydoclint
        entry: pydoclint
        language: python
        language_version: python3.10
        args: ["--style", "google"]
        additional_dependencies: [pydoclint]
        types: [python]
      - id: signoff-commit
        name: Sign-off Commit
        entry: bash
        language: system
        stages: [commit-msg]
        args:
          - -c
          - |
            COMMIT_MSG="$(git rev-parse --git-path COMMIT_EDITMSG)"
            NAME="$(git config user.name)"
            EMAIL="$(git config user.email)"
            SIGNOFF="Signed-off-by: $NAME <$EMAIL>"

            if ! grep -q "^$SIGNOFF" "$COMMIT_MSG"; then
              printf "\n$SIGNOFF\n" >> "$COMMIT_MSG"
            fi
        verbose: true
