[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "furiosa-perf"
version = "0.0.1"
description = "Furiosa Performance Benchmarkk Test Tool"
authors = [{name = "Furiosa AI Inc."}]
license = {text="MIT"}
readme = "README.md"
requires-python = ">=3.8"


dependencies = [
    "click>=8.0.0",
    "requests>=2.28.0",
    "PyYAML>=6.0.0",
    "pandas>=1.5.0",
    "numpy>=1.21.0",
    "matplotlib>=3.5.0",
    "psutil>=5.9.0",
    "jinja2>=3.1.0",
    "plotly>=5.18.0",
    "scipy>=1.10.0",
    "huggingface-hub",
    "types-requests",
    "pytablewriter"
]

[project.scripts]
furiosa-perf = "furiosa_perf.cli.main:cli"

[project.optional-dependencies]
furiosa-llm = ["furiosa-llm>=2025.3"]
vllm = ["vllm>0.9.2"]

dev = [
    "pytest",
    "black",
    "ruff",
    "pydoclint",
    "mypy",
    "pre-commit",
    "types-requests",
    "distro"
]

[tool.mypy]
packages = ["furiosa_perf"]
ignore_missing_imports = true
strict = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
pretty = true

[tool.pydoclint]
style = "google"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM", "C4", "S", "NPY", "PTH"]
ignore = ["E203", "E501"]
fixable = ["ALL"]

[tool.black]
line-length = 120
target-version = ["py310"]

[tool.setuptools.package-data]
furiosa_perf.report = ["_template/*", "_static/**/*"]
